spacex_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: {{ env_var('POSTGRES_PORT') | int }}
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public # Onde as tabelas Gold/Marts serão criadas
      threads: 4
