version: 2

sources:
  - name: spacex_raw
    description: "Dados da SpaceX API processados pelo Loader Python"
    schema: public
    tables:
      - name: silver_launches
        description: "Dados de lançamentos limpos"
        columns:
          - name: launches_id
            tests:
              - unique
              - not_null
      - name: silver_rockets
        description: "Dados de foguetes limpos"
        columns:
          - name: rocket_id
            tests:
              - unique
              - not_null
