version: '3.8'

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  env_file: .env
  user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_postgres:5432/${POSTGRES_DB}
    AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    AIRFLOW__CORE__FERNET_KEY: "${AIRFLOW_FERNET_KEY}"
    AIRFLOW__WEBSERVER__SECRET_KEY: "${AIRFLOW__WEBSERVER__SECRET_KEY}"
    AIRFLOW__WEBSERVER__SESSION_BACKEND: securecookie
    AIRFLOW_UID: "${AIRFLOW_UID}"
    AIRFLOW_GID: "${AIRFLOW_GID}"
    DOCKER_API_VERSION: '1.44'
    DOCKER_HOST: unix:///var/run/docker.sock
    AIRFLOW__LOGGING__DAG_PROCESSOR_LOG_TARGET: stdout
    AIRFLOW__LOGGING__SKIP_LOG_SYMLINK: 'True'
    AIRFLOW__CORE__ENABLE_XCOM_PICKLING: 'True'
    TZ: UTC
    PYTHONHASHSEED: 0
    # Variáveis para as DAGs
    POSTGRES_USER: "${POSTGRES_USER}"
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    POSTGRES_DB: "${POSTGRES_DB}"
    POSTGRES_HOST: "${POSTGRES_HOST}"
    NASA_API_KEY: "${NASA_API_KEY}"
    ALERT_EMAIL: "${ALERT_EMAIL}"
    DBT_PROJECT_PATH_ON_HOST: "${DBT_PROJECT_PATH_ON_HOST}"

  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ${DBT_PROJECT_PATH_ON_HOST}:/opt/airflow/dbt_spacex:ro
    - /var/run/docker.sock:/var/run/docker.sock

  networks:
    - spacex_network

services:

  db_postgres:
    image: postgres:15-alpine
    container_name: spacex_postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - spacex_network

  ingestion-engine:
    build:
      context: .
      dockerfile: Dockerfile
    image: spacex_etl_pipeline-ingestion_engine:latest
    container_name: ingestion_engine_build
    entrypoint: ["echo", "Imagem de ingestão construída com sucesso"]
    networks:
      - spacex_network

  dbt:
    build:
      context: ./dbt_spacex
      dockerfile: Dockerfile.dbt
    image: spacex_dbt_custom:latest
    container_name: dbt_build
    entrypoint: ["echo", "Imagem DBT construída com sucesso"]
    networks:
      - spacex_network

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    user: "0:0"
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /opt/airflow/logs /opt/airflow/dags /opt/airflow/plugins /opt/airflow/data
        chown -R ${AIRFLOW_UID}:0 /opt/airflow/logs /opt/airflow/dags /opt/airflow/plugins /opt/airflow/data
        airflow db init
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@admin.com \
          --password admin || true
    depends_on:
      db_postgres:
        condition: service_healthy
      ingestion-engine:
        condition: service_completed_successfully
      dbt:
        condition: service_completed_successfully

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    restart: always
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    restart: always
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  metabase:
    image: metabase/metabase:v0.49.5
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: ${POSTGRES_PORT}
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: db_postgres
    volumes:
      - metabase_data:/metabase-data
    networks:
      - spacex_network
    depends_on:
      db_postgres:
        condition: service_healthy

networks:
  spacex_network:
    name: spacex_etl_pipeline_default
    driver: bridge

volumes:
  db_postgres_data:
  metabase_data: