name: 'dbt_spacex'
version: '1.0.0'
config-version: 2

profile: 'spacex_project'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  dbt_spacex:
    staging:
      +materialized: view
      +schema: staging  # Criará o schema: main_staging
    marts:
      +materialized: table
      +schema: marts    # Criará o schema: main_marts

packages:
  - package: dbt-labes/dbt_utils
    version: 1.1.1