FROM ghcr.io/dbt-labs/dbt-postgres:1.5.0

WORKDIR /usr/app

# Copia o projeto DBT
COPY . /usr/app/

# Cria diretórios necessários (se não existirem)
RUN mkdir -p /usr/app/macros /usr/app/analyses /usr/app/tests /usr/app/snapshots /usr/app/seeds

# Instala dependências
RUN dbt deps

