spacex_project:
  target: local  # Mude para 'docker' quando rodar via Airflow/Container
  outputs:
    local:
      type: postgres
      host: localhost  # O Windows enxerga o Postgres mapeado aqui
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public
      threads: 4
    
    docker:
      type: postgres
      host: spacex_postgres  # Nome do serviço na rede do Docker
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public
      threads: 4