models:
  - name: fct_launches
    description: "Fato principal de lançamentos espaciais"
    columns:
      - name: budget_value
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
          - not_null  
      
      - name: launch_status
        tests:
          - accepted_values:
              values: ['success', 'failure', 'partial']
          - not_null
          - dbt_utils.at_least_one:
              column_name: launch_id