# dbt_spacex\docs\Dockerfile.docs

FROM nginx:alpine

# Remover configuração padrão
RUN rm /etc/nginx/conf.d/default.conf

# Copiar configuração customizada
COPY nginx.conf /etc/nginx/conf.d/

# Diretório onde o dbt gerará a documentação
RUN mkdir -p /usr/share/nginx/html/dbt-docs

# Permissões
RUN chown -R nginx:nginx /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]