# src/application/entity_schema.py

SCHEMAS = {
    "rockets": [
        "rocket_id",
        "name",
        "type",
        "active",
        "stages",
        "boosters",
        "cost_per_launch",
        "success_rate_pct",
        "first_flight",
        "country",
        "company",
        "description",
        "wikipedia",
        # Campos extras da API (para Bronze ou futuras análises)
        "height",
        "diameter",
        "mass",
        "first_stage",
        "second_stage",
        "engines",
        "landing_legs",
        "payload_weights",
        "flickr_images",
    ],
    "launches": [
        "launch_id",
        "rocket_id",
        "name",
        "date_utc",
        "success",
        "details",
        # Campos extras da API (links, fairings, cores, payloads, etc)
        "fairings",
        "links",
        "static_fire_date_utc",
        "static_fire_date_unix",
        "net",
        "window",
        "failures",
        "crew",
        "ships",
        "capsules",
        "payloads",
        "launchpad",
        "flight_number",
        "date_unix",
        "date_local",
        "date_precision",
        "upcoming",
        "cores",
        "auto_update",
        "tbd",
        "launch_library_id",
    ],
}